FROM node:16-alpine3.16

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./

ENV PORT=8080

ARG AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
ENV AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}

ARG AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

ARG AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}

COPY . ./

RUN npm install

RUN AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID npm run build

EXPOSE 8080
CMD [ "node", "dist/index.js" ]